// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdtokxd7UymKogdWoTfqt0YUMYwBpHr4w',
    appId: '1:692368598405:web:6ef191c5615537eb09d0ec',
    messagingSenderId: '692368598405',
    projectId: 'vendware-78f9b',
    authDomain: 'vendware-78f9b.firebaseapp.com',
    storageBucket: 'vendware-78f9b.appspot.com',
    measurementId: 'G-QB092B2RE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTMPV9eTzgZ4TaZImkPijEz_GdKzpTfg',
    appId: '1:692368598405:android:bb7660e1de5a814909d0ec',
    messagingSenderId: '692368598405',
    projectId: 'vendware-78f9b',
    storageBucket: 'vendware-78f9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3eBfjCWDmjR4syoZjfQABKAOMGQ2lHE0',
    appId: '1:692368598405:ios:abf90c536490c4e809d0ec',
    messagingSenderId: '692368598405',
    projectId: 'vendware-78f9b',
    storageBucket: 'vendware-78f9b.appspot.com',
    iosClientId: '692368598405-e92fsgbq88tae700ajmj7e2t89sv4v2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemoApp',
  );
}
